### ISSUE TITLE
missing "Statement of need" text in the documentation

### ISSUE THREAD

**Issue by istfer** [agrobioinfoservices/climatrends#11]
[JOSS review checklist](https://github.com/openjournals/joss-reviews/issues/4405) also requires the package documentation to include a "Statement of need" text. The summary section of the documentation briefly touches upon it but please consider including more distinct text that clearly states what problems the software is designed to solve and who the target audience is both in the [manuscript](https://github.com/AgrDataSci/climatrends/issues/6) and the documentation.

**Comment by kauedesousa** [comment]
A "Statement of need" of need is added here https://github.com/AgrDataSci/climatrends/commit/39b2d0e952d7069e011af421eb0219f018a0c160

**Comment by istfer** [comment]
This PR adds the "statement of need" to the paper, but the checklist also requires it to be in the documentation, could you add it there too?
