### ISSUE TITLE
can not find function 'get_power'

### ISSUE THREAD

**Issue by dlebauer** [agrobioinfoservices/climatrends#18]
I get an error when I run this code from the vignette:

``` r
library(climatrends)
    lonlat <- data.frame(lon = 129.19,
                         lat = 36.39)
    
    GDD(lonlat, 
        day.one = "2019-04-01",
        last.day = "2019-10-01",
        degree.days = 150, 
        return.as = "ndays")
#> Getting climate data from NASA POWER
#> Error in get_power(community = "ag", lonlat = c(129, 36, 132, 39), pars = c("T2M_MAX", : could not find function "get_power"
```

<sup>Created on 2022-08-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kauedesousa** [comment]
This issue is solved here https://github.com/AgrDataSci/climatrends/commit/83053e6c161b8396864bbeae7f86e22842612c45. The problem is that nasapower was not stated as a dependency for climatrends. Fixed.
