### ISSUE TITLE
comparison to other software/packages needed

### ISSUE THREAD

**Issue by istfer** [agrobioinfoservices/climatrends#8]
Per [JOSS review checklist](https://github.com/openjournals/joss-reviews/issues/4405), the software papers need to present the state of the field by providing a brief overview of other commonly-used software/packages and describe how this software compares to them. Please consider adding such a short paragraph to the text.

**Comment by kauedesousa** [comment]
A comparison with other software is added to new paper version here https://github.com/AgrDataSci/climatrends/commit/39b2d0e952d7069e011af421eb0219f018a0c160
